"""Warning-clean PyMuPDF import for Python 3.13.

PyMuPDF 1.27.2 is generated by SWIG. Its private extension creates three
builtin helper types without ``__module__`` (upstream swig/swig#2881), which
Python 3.13 warns about at import and again for ``swigvarlink`` at interpreter
shutdown. Import under an exact warning filter, then label the SWIG types both
now and at exit (PyMuPDF can create more while opening documents). Remove this
module once PyMuPDF ships generated types with ``__module__`` set.
"""

from __future__ import annotations

import atexit
import contextlib
import sys
import warnings

_SWIG_WARNING = r"builtin type (SwigPyPacked|SwigPyObject|swigvarlink) has no __module__ attribute"
_SWIG_TYPE_NAMES = {"SwigPyPacked", "SwigPyObject", "swigvarlink"}

with warnings.catch_warnings():
    warnings.filterwarnings("ignore", message=_SWIG_WARNING, category=DeprecationWarning)
    import pymupdf as pymupdf


def _candidate_swig_type(value: object) -> type | None:
    """Return the SWIG type represented by an instance OR by the type itself."""
    if isinstance(value, type) and value.__name__ in _SWIG_TYPE_NAMES:
        return value
    value_type = type(value)
    return value_type if value_type.__name__ in _SWIG_TYPE_NAMES else None


def _label_swig_types() -> None:
    """Give every live PyMuPDF SWIG heap type an owning module."""
    seen: set[type] = set()
    values: list[object] = []
    for module_name, module in tuple(sys.modules.items()):
        if module_name.startswith("pymupdf") and module is not None:
            values.extend(vars(module).values())
    for value in values:
        swig_type = _candidate_swig_type(value)
        if swig_type is None or swig_type in seen:
            continue
        seen.add(swig_type)
        if getattr(swig_type, "__module__", None) is None:
            with contextlib.suppress(TypeError):
                swig_type.__module__ = "pymupdf._mupdf"


_label_swig_types()
# Document operations can materialize additional SWIG wrapper values. atexit
# runs before extension-module finalization, so label those before Python checks
# builtin type metadata during shutdown.
atexit.register(_label_swig_types)

__all__ = ["pymupdf"]
